# Import SCons Environment
env = Environment()

# List of source files
source_files = [
    'OSFileReader.cpp',
    'CPUFileReader.cpp',
    'MemFileReader.cpp'
]

# Specify include directories
env.Append(CPPPATH=['../header', '../model'])

# Build the library
env.Library(target='src_obj', source=source_files)