name: Build with SCons

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install SCons
        run: |
          python -m pip install --upgrade pip
          pip install scons

      - name: Build with SCons
        run: scons

#      - name: Run tests
#        run: ./test_output.sh
