name: Build with SCons

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up Python (necessary if your build process depends on Python)
        with:
          python-version: '3.10'  # Use a specific Python version if needed

      - name: Install SCons
        run: |
          python -m pip install --upgrade pip
          pip install scons

      - name: Build with SCons
        run: scons  # Run SCons (ensure your SCons build file is correctly configured in the repo)

      # Optionally, add more steps if needed (e.g., run tests, upload artifacts)

